### PR TITLE
Stepper support

### PR DESCRIPTION
**Pull request by FilipDominec**
Complement for the changes contributed today to Telemetrix4RpiPico, with two examples for (a)synchronous stepper use

### CODE REVIEW

**Comment by MrYsLab** [comment]
I am going to add an alias for stepper_new called set_pin_mode stepper. This will keep the API consistent, but you may continue to use stepper_new, so your code does not change. I also need to bump up the version, create the API HTML, and update the documentation. When I complete these tasks, I will issue a new release and publish it to pypi.

**Comment by MrYsLab** [comment]
I also need to update the asyncio version [tmx-pico-aio](https://github.com/MrYsLab/tmx-pico-aio). This item and the one above will take me a few days to complete.

**Comment by FilipDominec** [comment]
Thank you. Following issue 8 it seems I shall further develop functions in a separate project. But stepper support in Tmx can be useful anyway.

**Comment by MrYsLab** [comment]
Question on your stepper interface. The endswitch_pin appears to be an optional parameter to stepper_new (python side). I am correct that it is optional?

**Comment by FilipDominec** [comment]
Absolutely. Running stepper without end switch is meaningful if its absolute position is determined by other means or is not needed at all (e.g. peristaltic pumps).

**Comment by MrYsLab** [comment]
@FilipDominec, I think I was too quick in accepting this pull request. I will be reverting the pull request until I have time to address the issues.

Here are the issues I have found:

```
def stepper_new(self, stepper_id, dir_pin, step_pin, endswitch_pin, disable_pin=255,
            motor_inertia=128):
```
1. None of the pins are being validated as "legal pins" contained within the [pico_pins dictionary](https://github.com/MrYsLab/telemetrix-rpi-pico/blob/03806bba948317e586b18ca2fa6b537cf965979a/telemetrix_rpi_pico/telemetrix_rpi_pico.py#L1334) . I do not know what happens on the RPi pico if an invalid pin number is specified. I believe the RPi Pico application crashes.
2. The endswitch pin must be specified with an integer value. It cannot be defined as end_switch_pin=None in the parameter list because it will cause the following line to throw an exception:
```
command_as_byte_list = [b for b in struct.pack(r'<BBBBBBI', *command)]
```
This is why I avoid using structs.
It also cannot be defined as 0 because this is a valid pin number.

3. The stepper_id value is not being validated within a given range.

I agree having stepper support would be a plus, but at this time, there are too many issues for me to deal with.

**Comment by MrYsLab** [comment]
I have maintained your changes [in this branch](https://github.com/MrYsLab/telemetrix-rpi-pico/tree/stepper).

**Comment by FilipDominec** [comment]
OK.

**Pull request merged**
